### ISSUE TITLE
The running encountered some issues.

### ISSUE THREAD

**Issue by 277CPS** [WENGSYX/CMIVQA_Baseline#8]
The environment and parameters have been modified according to the actual situation, but the following situation occurred when running main.py, and I don't know what went wrong. Also, the subtitle.json file in Baidu Netdisk has expired.

loading video features: 0it [00:00, ?it/s]
Not Load Example:  2920

**Comment by WENGSYX** [comment]
Hi, the url of subtitle.json file has be update: https://pan.baidu.com/s/1_4nUimt8oHhAX1Deaxp0_g?pwd=2024

This may be due to visual = load_video_features(os.path.join('data', 'train'), 768) in main.py, as the file path may be different. You can set it to your target video_features path (i.e., the path containing the *.npy files).
